# Generated by Django 4.1.5 on 2023-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_services_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_name', models.CharField(max_length=30)),
                ('product_brand', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=20)),
                ('product_stock', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
