# Generated by Django 4.1.5 on 2023-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='target',
            field=models.CharField(default='Men', max_length=20),
        ),
    ]
