# Generated by Django 4.1.5 on 2023-03-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=30)),
                ('product_brand', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
