# Generated by Django 4.1.5 on 2023-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
