# Generated by Django 4.1.5 on 2023-03-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_total_price_all_orders_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_orders',
            name='item',
        ),
        migrations.RemoveField(
            model_name='all_orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='all_orders',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.all_orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
