# Generated by Django 4.1.5 on 2023-03-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_orderitems_quantity_all_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_orders',
            name='payment_status',
            field=models.CharField(default='Pending Confirmation', max_length=50),
        ),
        migrations.AddField(
            model_name='all_orders',
            name='shipping_status',
            field=models.CharField(default='In Transit', max_length=50),
        ),
    ]
