# Generated by Django 4.1.5 on 2023-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
