# Generated by Django 4.1.5 on 2023-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_orders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
