# Generated by Django 4.1.5 on 2023-03-27 14:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_all_orders_quantity_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_orders',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+254713810930', max_length=128, region=None),
        ),
    ]
