# Generated by Django 4.1.5 on 2023-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_orders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
