# Generated by Django 4.1.5 on 2023-04-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_all_orders_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_orders',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(default='Pending Confirmation', max_length=50),
        ),
    ]
