# Generated by Django 4.1.5 on 2023-04-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_orderitems_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order_no',
        ),
    ]
