# Generated by Django 4.1.5 on 2023-04-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_orderitems_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='all_orders',
            name='payment_status',
            field=models.CharField(default='Pending Confirmation', max_length=50),
        ),
    ]
