# Generated by Django 4.1.5 on 2023-04-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_payments_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_orders',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
