# Generated by Django 4.1.5 on 2023-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_remove_all_orders_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='reviewed_status',
            field=models.BooleanField(default=False),
        ),
    ]
