# Generated by Django 4.1.5 on 2023-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_orderitems_reviewed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_orders',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='payment_status',
            field=models.CharField(default='Pending Confirmation', max_length=50),
        ),
    ]
