# Generated by Django 4.1.5 on 2023-04-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_all_orders_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_orders',
            name='shipping_status',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='shipping_status',
            field=models.CharField(default='Pending Dispatch', max_length=50),
        ),
    ]
