# Generated by Django 4.1.5 on 2023-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_all_orders_shipping_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ManyToManyField(to='products.all_orders'),
        ),
    ]
