# Generated by Django 4.1.5 on 2023-04-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_remove_orderitems_order_orderitems_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='products.all_orders'),
            preserve_default=False,
        ),
    ]
