# Generated by Django 4.1.5 on 2023-04-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_payments_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='order_id',
            new_name='order',
        ),
    ]
