# Generated by Django 4.1.5 on 2023-04-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_payments_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='order',
        ),
    ]
