# Generated by Django 4.1.5 on 2023-04-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_remove_payments_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
