# Generated by Django 4.1.5 on 2023-04-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_orderitems_parcel_collected_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='parcel_arrived_status',
            field=models.BooleanField(default=True),
        ),
    ]
