# Generated by Django 4.1.5 on 2023-04-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_orderitems_parcel_arrived_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='parcel_arrived_status',
            field=models.BooleanField(default=False),
        ),
    ]
