# Generated by Django 4.1.5 on 2023-04-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_orderitems_parcel_arrived_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='order',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='products.orderitems'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
