# Generated by Django 4.1.5 on 2023-04-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_reviews_order_alter_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orderitems'),
        ),
    ]
