# Generated by Django 4.1.5 on 2023-04-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_alter_reviews_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review',
            new_name='review_product',
        ),
    ]
