# Generated by Django 4.1.5 on 2023-04-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_alter_reviews_review_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
