# Generated by Django 4.1.5 on 2023-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_occupation', models.CharField(max_length=70)),
                ('quote', models.TextField(max_length=300)),
            ],
        ),
    ]
